# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 187bf9fd57f2c673ee3d9d301a9146a5de92531c29723745aaed3ea065e181162f4df256bcd4eb559910abaa596557dd3f4d4e7e3b1b1d2b5a1478779275ff45

test:
  secret_key_base: 09a6f807249f0431be0e47ff923874d2ee6c5c89484fd187cf280aef5c923977e570157fe2ccea188756494dc840d7573ea28e55f2552118147c2ed74e652011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
